-- Seed data for cron_jobs table
INSERT INTO cron_jobs (name, enabled, schedule, agent_id, description, state) VALUES
  ('Email Check', true, '{"kind":"cron","expr":"*/10 * * * *"}', 'bizops', 'Scans bob@ inbox every 10 minutes for new actionable emails. Alerts Jay via iMessage.', '{"lastStatus":"ok"}'),
  ('Lovedeep Error Logs Monitor', true, '{"kind":"cron","expr":"*/30 * * * *"}', 'devops', 'Checks NextWave and LeadGenJay n8n for failed executions. Notifies Lovedeep via Slack and email.', '{"lastStatus":"ok"}'),
  ('Instagram Stories Generator', true, '{"kind":"cron","expr":"0 20 * * *"}', 'main', 'Generates 3 Dan Kennedy-style Instagram story sequences, texts Jay options, auto-posts approved slides.', '{"lastStatus":"ok"}'),
  ('Task Board Maintenance', true, '{"kind":"cron","expr":"0 8,11,14,17,20 * * *"}', 'bizops', 'Silently reviews conversation history to mark tasks done, add new tasks, update ideas/decisions/trips.', '{"lastStatus":"ok"}'),
  ('8pm Calendar Preview', true, '{"kind":"cron","expr":"0 20 * * *"}', 'main', 'Sends Jay a formatted iMessage preview of tomorrow''s calendar events.', '{"lastStatus":"ok"}'),
  ('Check Jake Meta Report Feedback', true, '{"kind":"cron","expr":"0 */2 * * *"}', 'main', 'Monitors for Jake Behler reply to Meta Ads report. Summarizes feedback to Jay when received.', '{"lastStatus":"ok"}'),
  ('Overnight Work Session 1 (11pm)', true, '{"kind":"cron","expr":"0 23 * * *"}', 'dev', 'Full pipeline review: GMaps scraping, enrichment, B2B verification, n8n, Reacher proxy, Docker health.', '{"lastStatus":"ok"}'),
  ('Zeus Night Health Check', true, '{"kind":"cron","expr":"0 23 * * *"}', 'devops', 'Checks Zeus for exited containers, disk >90%, memory <10GB, PgBouncer errors. Restarts if needed.', '{"lastStatus":"ok"}'),
  ('n8n Health Check', true, '{"kind":"cron","expr":"0 0,8,16 * * *"}', 'devops', 'Checks both n8n instances hourly for errors. Alerts Jay for critical workflows, emails Lovedeep.', '{"lastStatus":"ok"}'),
  ('GMaps + B2B Health Check', true, '{"kind":"cron","expr":"0 0,8,16 * * *"}', 'main', 'Checks GMaps scraping, enrichment, verification pipelines. Ghost run detection. Auto-restarts stalled scraper.', '{"lastStatus":"ok"}'),
  ('Zeus Data Pipeline Health Check', true, '{"kind":"cron","expr":"0 0,8,16 * * *"}', 'devops', 'Checks creators-db, GMaps scraper status, alerts on container failures or 48hr sync gaps.', '{"lastStatus":"ok"}'),
  ('Overnight Work Session 2 (2am)', true, '{"kind":"cron","expr":"0 2 * * *"}', 'dev', 'Continues proactive backlog work. Logs progress silently to overnight-log.md.', '{"lastStatus":"ok"}'),
  ('GitHub Secret Scanner', true, '{"kind":"cron","expr":"0 2 * * *"}', 'devops', 'Scans all repos for hardcoded secrets. Auto-fixes JS/TS/Python files with syntax validation.', '{"lastStatus":"ok"}'),
  ('Overnight Work Session 3 (5am)', true, '{"kind":"cron","expr":"0 5 * * *"}', 'dev', 'Final overnight session. Wraps up work, prepares morning-briefing.md for Jay.', '{"lastStatus":"ok"}'),
  ('Viral Content Daily Report', true, '{"kind":"cron","expr":"0 6 * * 1-5"}', 'main', 'Searches viral content in cold email, n8n, AI automation. Generates PDF, uploads to Drive, DMs Sujeet.', '{"lastStatus":"ok"}'),
  ('Zeus Morning Health Check', true, '{"kind":"cron","expr":"0 6 * * *"}', 'devops', 'Same Zeus checks as night: containers, disk, memory, PgBouncer. Reports to Jay.', '{"lastStatus":"ok"}'),
  ('Model Preference Reset Check', true, '{"kind":"cron","expr":"0 7 * * *"}', 'main', 'Checks if Claude Sonnet is healthy and restores it as primary model if on fallback.', '{"lastStatus":"ok"}'),
  ('Reddit Account Warmup', true, '{"kind":"cron","expr":"0 7,10,13,16,19 * * *"}', 'main', 'Phase 1 warmup for u/BobTheAssistant_AI: upvotes, genuine comments in casual subs, building karma.', '{"lastStatus":"ok"}'),
  ('n8n Daily Health Check', true, '{"kind":"cron","expr":"0 7 * * *"}', 'devops', 'Runs full n8n health check script, emails Jay and Lovedeep with error summary.', '{"lastStatus":"ok"}'),
  ('Skool Daily Post Ideas', true, '{"kind":"cron","expr":"0 7 * * *"}', 'main', 'Generates 9 Skool posts (3 per community) using viral research. Emails Jay for approval.', '{"lastStatus":"ok"}'),
  ('Birthday Check', true, '{"kind":"cron","expr":"0 8 * * *"}', 'bizops', 'Checks birthdays.md for today. Texts Jay immediately with reminder.', '{"lastStatus":"ok"}'),
  ('YouTube Comment Check', true, '{"kind":"cron","expr":"0 8,14,18 * * *"}', 'main', 'Scans YouTube for new comments. Auto-deletes spam, auto-replies to compliments, flags complex ones.', '{"lastStatus":"ok"}'),
  ('Skool Comment Check', true, '{"kind":"cron","expr":"0 9,17 * * *"}', 'main', 'Scans all 3 Skool communities for unanswered posts. Writes drafts, emails Jay numbered list for approval.', '{"lastStatus":"ok"}'),
  ('Morning Roundup (9am M-F)', true, '{"kind":"cron","expr":"0 9 * * 1-5"}', 'main', 'Consolidated morning briefing: inbox review, overnight summary, n8n health. One iMessage to Jay.', '{"lastStatus":"ok"}'),
  ('5pm Daily Review (M-F)', true, '{"kind":"cron","expr":"0 17 * * 1-5"}', 'bizops', 'Reviews Slack mentions, Notion tasks, Asana, Gmail, Bob task board. Sends prioritized summary to Jay.', '{"lastStatus":"ok"}'),
  ('Weekly Meta Ads Report', true, '{"kind":"cron","expr":"0 10 * * 2"}', 'main', 'Pulls Hyros + Meta API data, generates PDF report, uploads to Drive, DMs Jake Behler on Slack.', '{"lastStatus":"ok"}')
ON CONFLICT DO NOTHING;
